### ISSUE TITLE
Bracket Environment Proposal

### ISSUE THREAD

**Issue by mpage** [brkt/brkt-cli#396]
This proposal introduces the concept of an environment as a first class configuration object in the CLI. An environment encapsulates the set of configuration options that are tied to a specific Yeti backend. Initially, this will consist of:

* signing-key
* public-api-addr
* yetiapi-addr
* keyserver-addr (nee hsmproxy-addr)
* token

Users can define multiple environments, though only one may be active at any point in time. Other subcommands would pull defaults from the currently active environment. For example, when this proposal is coupled with the existing config support, the number of arguments required for  `encrypt-gce-image` command is reduced to 3:

    brkt encrypt-gce-image --encrypted-image-name hi-matt --image-project ubuntu-os-cloud ubuntu-1404-trusty-v20160406

Sample usage:

    # Create stage and prod environments
    > brkt env create stage
    > brkt env create prod
    >

    # Configure the stage environment
    > brkt config set env.stage.api-addr yetiapi.stage.mgmt.brkt.com
    > brkt config set env.stage.public-api-addr api.stage.mgmt.brkt.com
    > brkt config set env.stage.hsmproxy hsmproxy.stage.mgmt.brkt.com
    > brkt config set env.stage.signing-key ~/.brkt/stage.key
    >

    # Alternatively, we could not use the config subcommand to configure environments. 
    # Instead, we could combine creation and modification.
    > brkt env set stage --api-addr yetiapi.stage.mgmt.brkt.com 
    > brkt env set stage --hsmproxy-addr hsmproxy.stage.mgmt.com 
    > brkt env set stage --public-api-addr api.mgmt.brkt.com 
    > brkt env set stage --signing-key ~/.brkt/stage.key
    > brkt env set prod
    >

    # Set the active environment to stage
    > brkt env use stage
    >

    # List  all environments
    >  brkt env list
    * stage
      prod
    >

    # Get the details of an environment
    > brkt env get stage
    api-addr=yetiapi.stage.mgmt.brkt.com
    hsmproxy-addr=hsmproxy.stage.mgmt.com
    public-api-addr=api.mgmt.brkt.com
    signing-key=~/.brkt/stage.key
    >

    # Delete an environment
    > brkt env delete prod
    >

Questions for the reader:

1. Does the proposed syntax make sense?
2. Which of the alternatives for configuring an environment do you prefer?

**Comment by dramdass** [comment]
1. Proposed syntax makes sense to me
2. I think proposal 2 is slightly more readable but in reality I think most developers will run a script of whatever 4 commands or just copy/paste/run so I don't think it's worth it to do more work with the `env` subcommand as opposed to using the already existing `config` subcommand. I think the subset of people who will do specific configurations to their environments will be probably be familiar with the `config` subcommand

Additionally, whatever environment is in use (in the case of multiple configured environments) should be printed as the first line in the output of whatever `brkt` subcommand is run.

**Comment by bburtin** [comment]
What is "addr"?  If it's just the host, we should probably call it "host", to be clearer.  According to the URL spec, the official combination of host:port is actually called the authority, although that sounds kind of academic.

**Comment by mpage** [comment]
Talked with Boris and Dennis a bit more about this. Consensus was to restrict the environment to the set of addresses that make up a yeti backend.

It's not just the host. We let users specify an arbitrary "<host>:<port>" string for each service that the metavisor needs to talk to. Is "hostport" more intuitive? Authority is less intuitive than either "addr" or "hostport".

**Comment by krishnanrs** [comment]
"address" or "endpoint" is a more logical term for a host:port combination.

**Comment by mpage** [comment]
Settled on server.
