### ISSUE TITLE
No GCE equivalent to the 'validate' flag for the AWS encrypt/update 

### ISSUE THREAD

**Issue by gcallaghan** [brkt/brkt-cli#400]
Right  there is no way to disable validation based on network calls for GCE. We currently have no GCE equivalent to the 'validate' flag for the AWS encrypt/update commands. Since we don't support a custom CA cert (for brkt-cli talking to YetI), this means that all GCE encrypt/update commands may fail.

**Comment by bburtin** [comment]
Fixed in commit 3c20c1e39aca4f4e5e3fde68c62e097de9cfa710.
