### ISSUE TITLE
--signing-key not recognized even with cryptography package installed

### ISSUE THREAD

**Issue by hsson** [brkt/brkt-cli#721]
When trying to use the `brkt make-token --signing-key <some key>` I get the following output:
```
> brkt make-token --signing-key my_cert.pem
usage: brkt [-h] [-v] [--version] [--no-check-version]
            {auth,aws,config,gcp,make-key,make-token,make-user-data,vmware}
            ...
brkt: error: unrecognized arguments: --signing-key
```

I was told it only works if the cryptography python package is installed, so I installed it using `pip install cryptography`. However, running the same `brkt make-token` command still doesn't work as the `--signing-key` flag is not recognized. Also, there should be some clearer documentation about the fact that the cryptograpghy package is required.

This was done using version 1.0.10

**Comment by krishnanrs** [comment]
Not sure in which version of brkt-cli the change was made, however the signing key was made a positional argument instead of being passed via a command line flag
`brkt make-token [-h] [--brkt-tag NAME=VALUE] [--root-url URL]
                       [--claim NAME=VALUE] [--customer UUID] [--exp DURATION]
                       [--nbf TIMESTAMP] [--out PATH]
                       [SIGNING-KEY-PATH]`
Can you just run a {brkt make-token --help} and verify the help output?

**Comment by bonzotronix** [comment]
True that the signing key is a positional arg now.  I'm OK with that (also OK if someone wants to change that to use --signing-key instead).
This worked for me:
```pip install cryptography
./brkt make-token --claim foo=bar --out token.out ./newer_jwt_signing_private.pem
```
